title: "Bayesian PDE Inverse Problems with Certified Uncertainty"
description: "A comprehensive framework for solving inverse problems in partial differential equations using Bayesian methods with mathematically certified uncertainty quantification."
baseurl: "/Bayesian_PDE_Inverse_Problems_with_Certified_Uncertainty"
url: "https://tani843.github.io"

# Academic styling
markdown: kramdown
highlighter: rouge
theme: minima

# Enhanced Navigation structure with Research dropdown
header_pages:
  - methodology.md
  - implementation.md
  - results.md
  - documentation.md
  - about.md

# Research section pages (for dropdown menu)
research_pages:
  - theoretical-results.md
  - benchmarks.md
  - applications.md
  - publications.md

# Academic metadata
author:
  name: "Your Name"
  email: "your.email@university.edu"

# Social and academic links
social_links:
  github: tani843
  
# SEO and academic features
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Academic styling preferences
minima:
  skin: classic
  
# Enhanced math and visualization rendering
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# MathJax configuration for advanced mathematical notation
mathjax:
  source: https://polyfill.io/v3/polyfill.min.js?features=es6
  config: |
    window.MathJax = {
      tex: {
        inlineMath: [['$', '$'], ['\\(', '\\)']],
        displayMath: [['$$', '$$'], ['\\[', '\\]']],
        processEscapes: true,
        processEnvironments: true,
        packages: {'[+]': ['ams', 'color', 'boldsymbol']}
      },
      options: {
        ignoreHtmlClass: 'tex2jax_ignore',
        processHtmlClass: 'tex2jax_process'
      }
    };

# Plotly.js configuration for interactive visualizations
plotly:
  cdn: https://cdn.plot.ly/plotly-latest.min.js

# Include research-specific JavaScript libraries
include_research_js: true

# Collections for organizing research content
collections:
  theoretical_results:
    output: true
    permalink: /:collection/:name/
  benchmarks:
    output: true  
    permalink: /:collection/:name/
  applications:
    output: true
    permalink: /:collection/:name/